import Head from "next/head";
import Fitur from "../components/Fitur/Fitur";
import Home from "../components/Home/Home";
import Kontak from "../components/Kontak/Kontak";
import Navbar from "../components/Navbar/Navbar";

import styles from "../styles/Index.module.css";

export default function Homepage() {
	return (
		<div className={styles.container}>
			<Head>
				<title>AcaraJo</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<nav>
				<Navbar />
			</nav>

			<main className={styles.main}>
				<Home />
				<Fitur />
				<Kontak />
			</main>

			<footer className={styles.footer}>
				<p>&#169; all rights reserved by AcaraJo.</p>
			</footer>
		</div>
	);
}
